### ISSUE TITLE
Wait wait WAIT and WAIT!

### ISSUE THREAD

**Issue by uvsq22401387** [ModdingTwins/PocketGameCore#2]
Hello MTwinz,

That isn't your plugin, you aren't the plugin Author, The real author is yPublicyFun.
Maybe you translated the plugin , but you have right to claim this plugin,

I have a proof:
There is the real plugin!!:

https://github.com/yPublicyFun/LobbyCore
**SORYY BUT YOU CAN'T CLAIM THIS !**

**Comment by Wolfkid200444** [comment]
OHHHHHHHHHHHHHH
